name: Deploy Website

on:
  push:
    branches:
      - main # You can change this to your default branch name (usually `master` or `main`)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-website .


    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.1.0
      with:
        branch: gh-pages # The branch you want to deploy to
        folder: . # Directory to deploy (root of your project in this case)
        token: ${{ secrets.GITHUB_TOKEN }}

